name: flutter_coverage_badge
description: Flutter Coverage Badge
version: 0.0.1+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

executables:
  flutter_coverage_badge:

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  glob: ^2.0.2
  args: ^2.3.0
  lcov:
    git:
      url: git@github.com:amondnet/lcov.dart.git


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
